# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [1]:
# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False

def fun(l1):
    return l1[0] == l1[-1]

fun(numbers_y)

False





# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [2]:
#code here

import numpy as np 
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])

arr3=arr1+arr2
arr4=arr1*arr2

print(arr3,arr4)

[ 2  4  6  8 10] [ 1  4  9 16 25]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [3]:
#code here
arr=np.arange(12)
arr.reshape(3,4)

arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])


arr5 = np.hstack((arr1, arr2))
arr6 = np.vstack((arr1, arr2))
print(arr5)
print(arr6) 

[1 2 3 4 5 1 2 3 4 5]
[[1 2 3 4 5]
 [1 2 3 4 5]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [4]:
import string
def products():
    print("----Welcome User!----")
    print("----Shopping List----")
    print("1-Soap----")
    print("2-liquor----")
    print("3-kerosene----")
#Code here
shopping_cart=[]
products()
i=input('Enter a product (Enter Q for checkout)')

while i.lower()!='q':
    num=int(i)
    if (num<1 and num>3):
        print('Please Enter a Valid Product!')
    else:
        if num==1:
            shopping_cart.append('Soap')
        if num==2:
            shopping_cart.append('liquor')
        if num==3:
            shopping_cart.append('kerosene')
    i=input('Enter a product (Enter Q for checkout)')
    
print("__________________________")   
print('Goodbye!')
print("__________________________")
print(shopping_cart)
                    
    
    

----Welcome User!----
----Shopping List----
1-Soap----
2-liquor----
3-kerosene----


__________________________
Goodbye!
__________________________
[]


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [80]:
def classify_emails(emails):
    imp_list = ['student', 'bank', 'job']
    promo_list = ['restaurant', 'hotel', 'tour']
    spam_list = ['offer', 'spam', 'hello']

    imp = []
    promo = []
    spam = []

    for mail in emails:
        if any(keyword in mail for keyword in imp_list):
            imp.append(mail)
        elif any(keyword in mail for keyword in promo_list):
            promo.append(mail)
        elif any(keyword in mail for keyword in spam_list):
            spam.append(mail)

    print("Important emails:")
    for mail in imp:
        print(mail)

    print("\nPromotional emails:")
    for mail in promo:
        print(mail)

    print("\nSpam emails:")
    for mail in spam:
        print(mail)

emails = [
    'hello, I would like you to offer this product',
    'dear student, your GPA has been evaluated',
    'restaurant open! close to H11/1'
]

classify_emails(emails)


Important emails:
dear student, your GPA has been evaluated

Promotional emails:
restaurant open! close to H11/1

Spam emails:
hello, I would like you to offer this product


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [5]:
#code here
english_to_spanish = {
    "hello": "hola",
    "world": "mundo",
    "goodbye": "adiós",
    "cat": "gato",
    "dog": "perro"
}

english_word="l"
# Accessing translations
while english_word!='e':
    english_word=input("Enter a word for translation - (press E to exit)")
    spanish_translation = english_to_spanish.get(english_word.lower(), "Translation not available")
    print(spanish_translation)


Translation not available


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [6]:
import pandas as pd

# URL of the dataset
url = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"

# Read the CSV file into a DataFrame
df = pd.read_csv(url)

# Display the first few rows of the DataFrame
print(df.head())


   Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37  


In [7]:
df['Global_Sales'].sum()

8920.44

In [8]:
df.loc[df['Global_Sales'].argmax()]

Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object

In [14]:
print(df[['NA_Sales','JP_Sales','EU_Sales','Other_Sales']].astype(float).mean())


NA_Sales       0.264667
JP_Sales       0.077782
EU_Sales       0.146652
Other_Sales    0.048063
dtype: float64


In [19]:
genre_series = df['Genre']
global_sales_series = df['Global_Sales']
sorted_indices = global_sales_series.argsort()
sorted_genre_series = genre_series.iloc[sorted_indices]
print(sorted_genre_series.head())

16597     Platform
16188         Misc
16187       Puzzle
16186     Strategy
16185    Adventure
Name: Genre, dtype: object


In [20]:
df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [ ]:
# * Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
# * Display last 10 rows.
# * Determine the top 3 gaming platforms with the highest global sales.
# * Calculate the market share (percentage of global sales) for each genre.
# * Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [65]:
# * Calculate the market share (percentage of global sales) for each genre.
df.groupby('Genre')['Global_Sales'].value_counts()

Genre     Global_Sales
Action    0.02            187
          0.03            154
          0.04            118
          0.06            117
          0.01            107
                         ... 
Strategy  2.40              1
          2.63              1
          2.85              1
          2.73              1
          5.45              1
Name: count, Length: 2492, dtype: int64

In [49]:
# * Determine the top 3 gaming platforms with the highest global sales.
df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False)

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Wii      926.71
DS       822.49
PS       730.66
GBA      318.50
PSP      296.28
PS4      278.10
PC       258.82
XB       258.26
GB       255.45
NES      251.07
3DS      247.46
N64      218.88
SNES     200.05
GC       199.36
XOne     141.06
2600      97.08
WiiU      81.86
PSV       61.93
SAT       33.59
GEN       28.36
DC        15.97
SCD        1.87
NG         1.44
WS         1.42
TG16       0.16
3DO        0.10
GG         0.04
PCFX       0.03
Name: Global_Sales, dtype: float64

In [22]:
df.head()

Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [37]:
grouped_by_genre=df.groupby('Genre')
grouped_by_genre[['NA_Sales','JP_Sales','EU_Sales','Other_Sales']].sum()



NA_Sales  JP_Sales  EU_Sales  Other_Sales
Genre                                                  
Action          877.83    159.95    525.00       187.38
Adventure       105.80     52.07     64.13        16.81
Fighting        223.59     87.35    101.32        36.68
Misc            410.24    107.76    215.98        75.32
Platform        447.05    130.77    201.63        51.59
Puzzle          123.78     57.31     50.78        12.55
Racing          359.42     56.69    238.39        77.27
Role-Playing    327.28    352.31    188.06        59.61
Shooter         582.60     38.28    313.27       102.69
Simulation      183.31     63.70    113.38        31.52
Sports          683.35    135.37    376.85       134.97
Strategy         68.70     49.46     45.34        11.36

In [43]:
df1=df.sort_values(by='NA_Sales',ascending=False)
df1['Genre'].head(1)


0    Sports
Name: Genre, dtype: object